DIAGNOSIS_TO_PHENOTYPE =[
{'label': 'pancreatic acinar cell carcinoma',
 'name': 'Acinar cell carcinoma',
 'ontology_term': 'MONDO:0006346',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0006346&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0006346'},
{'label': 'adenocarcinoma in situ',
 'name': 'Adenocarcinoma in situ, NOS',
 'ontology_term': 'MONDO:0003218',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0003218&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0003218'},
{'label': 'tubulovillous adenoma',
 'name': 'Adenocarcinoma in tubulovillous adenoma',
 'ontology_term': 'MONDO:0024661',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0024661&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0024661'},
{'label': 'adenocarcinoma',
 'name': 'Adenocarcinoma with mixed subtypes',
 'ontology_term': 'MONDO:0004970',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0004970&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0004970'},
{'label': 'adenocarcinoma',
 'name': 'Adenocarcinoma, NOS',
 'ontology_term': 'MONDO:0004970',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0004970&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0004970'},
{'label': 'intestinal type adenocarcinoma',
 'name': 'Adenocarcinoma, intestinal type (C16._)',
 'ontology_term': 'MONDO:0006254',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0006254&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0006254'},
{'label': 'adenosquamous carcinoma',
 'name': 'Adenosquamous carcinoma',
 'ontology_term': 'MONDO:0006074',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0006074&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0006074'},
{'label': 'atypical carcinoid tumor',
 'name': 'Atypical carcinoid tumor',
 'ontology_term': 'MONDO:0006095',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0006095&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0006095'},
{'label': 'carcinoid tumor (disease)',
 'name': 'Carcinoid tumor, NOS [including of appendix]',
 'ontology_term': 'MONDO:0005369',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0005369&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0005369'},
{'label': 'carcinoid tumor (disease)',
 'name': 'Carcinoid tumor, NOS',
 'ontology_term': 'MONDO:0005369',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0005369&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0005369'},
{'label': 'undifferentiated pancreatic carcinoma with osteoclast-like giant '
          'cells',
 'name': 'Carcinoma with osteoclast-like giant cells',
 'ontology_term': 'MONDO:0006479',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0006479&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0006479'},
{'label': 'carcinoma',
 'name': 'Carcinoma, NOS',
 'ontology_term': 'MONDO:0004993',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0004993&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0004993'},
{'label': 'cholangiocarcinoma',
 'name': 'Cholangiocarcinoma (C22.1, C24.0)',
 'ontology_term': 'MONDO:0019087',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0019087&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0019087'},
{'label': 'cystadenocarcinoma',
 'name': 'Cystadenocarcinoma, NOS',
 'ontology_term': 'MONDO:0005596',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0005596&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0005596'},
{'label': 'pancreatic gastrinoma',
 'name': 'Gastrinoma, malignant',
 'ontology_term': 'MONDO:0024638',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0024638&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0024638'},
{'label': 'malignant ependymoma',
 'name': 'Glucanoma, malignant (C25._)',
 'ontology_term': 'MONDO:0021191',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0021191&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0021191'},
{'label': 'pancreatic ductal adenocarcinoma',
 'name': 'Infiltrating duct carcinoma, NOS (C50._)',
 'ontology_term': 'MONDO:0005184',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0005184&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0005184'},
{'label': 'pancreatic insulinoma',
 'name': 'Insulinoma, malignant (C25._)',
 'ontology_term': 'MONDO:0024677',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0024677&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0024677'},
{'label': 'pancreatic intraductal papillary-mucinous neoplasm with an '
          'associated invasive carcinoma',
 'name': 'Intraductal papillary adenocarcinoma with invasion (C50._)',
 'ontology_term': 'MONDO:0004481',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0004481&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0004481'},
{'label': 'pancreatic intraductal papillary-mucinous neoplasm with an '
          'associated invasive carcinoma',
 'name': 'Intraductal papillary-mucinous carcinoma, invasive (C25._)',
 'ontology_term': 'MONDO:0004481',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0004481&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0004481'},
{'label': 'pancreatic intraductal papillary-mucinous neoplasm',
 'name': 'Intraductal papillary-mucinous carcinoma, non-invasive (C25._)',
 'ontology_term': 'MONDO:0004286',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0004286&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0004286'},
{'label': 'invasive breast carcinoma',
 'name': 'Invasive carcinoma of no special type (C50._) [BREAST ONLY]',
 'ontology_term': 'MONDO:0006256',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0006256&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0006256'},
{'label': 'pancreatic carcinoma with mixed differentiation',
 'name': 'Mixed pancreatic endocrine and exocrine tumor, malignant (C25._)',
 'ontology_term': 'MONDO:0044727',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0044727&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0044727'},
{'label': 'mucinous adenocarcinoma',
 'name': 'Mucinous adenocarcinoma [2018+: USE 8253 FOR LUNG ONLY]',
 'ontology_term': 'MONDO:0004957',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0004957&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0004957'},
{'label': 'mucinous adenocarcinoma',
 'name': 'Mucinous adenocarcinoma',
 'ontology_term': 'MONDO:0004957',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0004957&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0004957'},
{'label': 'high grade malignant neoplasm',
 'name': 'NEOPLASM, malignant',
 'ontology_term': 'MONDO:0020665',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0020665&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0020665'},
{'label': 'neuroendocrine carcinoma',
 'name': 'Neuroendocrine carcinoma, NOS',
 'ontology_term': 'MONDO:0002120',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0002120&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0002120'},
{'label': 'papillary adenocarcinoma',
 'name': 'Noninfiltrating intraductal papillary adenocarcinoma (C50._)',
 'ontology_term': 'MONDO:0002512',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0002512&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0002512'},
{'label': 'pancreatic endocrine carcinoma',
 'name': 'Pancreatic endocrine tumor, malignant (C25._)',
 'ontology_term': 'MONDO:0005893',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0005893&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0005893'},
{'label': 'signet ring cell carcinoma',
 'name': 'Signet ring cell carcinoma',
 'ontology_term': 'MONDO:0005092',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0005092&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0005092'},
{'label': 'solid pseudopapillary carcinoma of pancreas',
 'name': 'Solid pseudopapillary carcinoma (C25._)',
 'ontology_term': 'MONDO:0018525',
 'provenance': 'https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0018525&groupField=iri&exact=on&start=0&ontology=mondo',
 'source': 'http://purl.obolibrary.org/obo/MONDO_0018525'}]

PHENOTYPES = {t['name']: t for t in DIAGNOSIS_TO_PHENOTYPE}
print(PHENOTYPES.keys())



    diagnoses_emitter = emitter('phenotype_from_bcc_diagnosis', output_dir='source/reference')

    for t in DIAGNOSIS_TO_PHENOTYPE:
        diagnoses_emitter.write(
            {
                "_id": "Phenotype:{}".format(t['ontology_term']),
                "gid": "Phenotype:{}".format(t['ontology_term']),
                "label": "Phenotype",
                "data": {
                    "term_id": t['ontology_term'],
                    "term": t['label'],
                    "name": t['name']
                }
            }
        )
    diagnoses_emitter.close()
